authors = ["Gabriel Wu <wuzihua@pku.edu.cn> and contributors"]
name = "Taichi"
uuid = "6a7659b3-242e-4b14-83a6-15a101e52794"
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Jl2Py = "fe5dac85-8b54-4abc-b8de-3413e1fbc3b7"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
CondaPkg = "0.2"
Jl2Py = "0.1"
PythonCall = "0.9"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
