name = "Taichi"
uuid = "6a7659b3-242e-4b14-83a6-15a101e52794"
authors = ["Gabriel Wu <wuzihua@pku.edu.cn> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
